# Generated by Django 3.2.4 on 2021-06-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ajax_Filter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type_child',
            old_name='natypeme',
            new_name='type',
        ),
    ]
