# Generated by Django 3.2.4 on 2021-06-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ajax_Filter', '0002_rename_natypeme_type_child_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ajax_Filter.type_child')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ajax_Filter.product')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ajax_Filter.type_parrent')),
            ],
        ),
    ]
