# Generated by Django 3.2.4 on 2021-06-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay_Mob', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
