# Generated by Django 3.2.4 on 2021-06-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay_Mob', '0004_auto_20210615_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.PositiveIntegerField(default=0)),
                ('details', models.TextField()),
            ],
        ),
    ]
