# Generated by Django 3.2.4 on 2021-06-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay_Mob', '0007_remove_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
